services:
  backend:
    build:
      context: ./back
    container_name: django_backend
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./front/frontend
    container_name: vue_frontend
    volumes:
      - ./front/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  celery_worker:
    build:
      context: ./back
    container_name: celery_worker
    command: celery -A config worker -l info
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
