services:
  # Serwis Redis
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped

  # Serwis Backendu (Django)
  backend:
    build:
      context: ./back
    container_name: django_backend
    volumes:
      # Montowanie kodu źródłowego, aby zmiany były widoczne bez przebudowywania obrazu
      - ./back:/app
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    depends_on:
      # Uruchom backend dopiero, gdy db i redis będą gotowe
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  # Serwis Frontendu (Vue)
  frontend:
    build:
      context: ./front/frontend
    container_name: vue_frontend
    volumes:
      # Montowanie kodu źródłowego dla Hot-Reloading
      - ./front/frontend:/app
      # Zapobiega nadpisaniu node_modules przez lokalny katalog (ważne na Windows)
      - /app/node_modules
    ports:
      # Port deweloperski Vite
      - "5173:5173"
    depends_on:
      - backend

  # Serwis Celery Worker
  celery_worker:
    build:
      context: ./back
    container_name: celery_worker
    command: celery -A config worker -l info
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    depends_on:
      - redis
      - backend