services:
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped

  backend:
    build:
      context: ./back
    container_name: django_backend
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    depends_on:
      - redis
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build:
      context: ./front/frontend
    container_name: vue_frontend
    volumes:
      - ./front/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  celery_worker:
    build:
      context: ./back
    container_name: celery_worker
    command: celery -A config worker -l info
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    depends_on:
      - redis
      - backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
